const aimlprojects=[
    {
        id:1,
        title:'Satellite    Image Segmentation',
        developer:'Vikas Kumar',
        projectImage:'/projects/aiml/satellite.jpg',
        imageUrl:'https://media.licdn.com/dms/image/C4D03AQFlLMURb7sKxQ/profile-displayphoto-shrink_400_400/0/1655796639359?e=1703116800&v=beta&t=7GDdzIurH1R25Bjo10mwCn8M4nrMLqmf2IBFoAe4TA4',
        profileLink:'https://www.linkedin.com/in/vikaskumar142001/',
        projectLink:'https://www.kaggle.com/code/vikasgenisyss/model',
    },
    {
        id:2,
        title:'Movie Recommendations System',
        developer:'Vikas Kumar',
        projectImage:'/projects/aiml/movie.jpg',
        imageUrl:'https://media.licdn.com/dms/image/C4D03AQFlLMURb7sKxQ/profile-displayphoto-shrink_400_400/0/1655796639359?e=1703116800&v=beta&t=7GDdzIurH1R25Bjo10mwCn8M4nrMLqmf2IBFoAe4TA4',
        profileLink:'https://www.linkedin.com/in/vikaskumar142001/',
        projectLink:'https://github.com/VikasKumar2001/Movie-Recommendation-System',
    },
    {
        id:3,
        title:'Resume Parser',
        developer:'Vikas Kumar',
        projectImage:'/projects/aiml/resume.jpg',
        imageUrl:'https://media.licdn.com/dms/image/C4D03AQFlLMURb7sKxQ/profile-displayphoto-shrink_400_400/0/1655796639359?e=1703116800&v=beta&t=7GDdzIurH1R25Bjo10mwCn8M4nrMLqmf2IBFoAe4TA4',
        profileLink:'https://www.linkedin.com/in/vikaskumar142001/',
        projectLink:'https://github.com/VikasKumar2001/CodeClause_Resume_Parser',
    },
    {
        id:5,
        title:'SocialKArt',
        developer:'Aditya Singh',
        projectImage:'/projects/aiml/socialKart.jpg',
        imageUrl:'',
        profileLink:'http://linkedin.com/in/zendrixate/',
        projectLink:'http://github.com/YusiferZendric/SocialKart',
    },
]
const arvrprojects=[
    {
        id:1,
        title:'ZenVerse',
        developer:'Akshat Shukla',
        projectImage:'/projects/arvr/zenverse.png',
        imageUrl:'',
        profileLink:'https://www.linkedin.com/in/as-akshat-shukla/',
        projectLink:'https://github.com/Nemesis-AS/nscc-innotech24-vr',
    }
]
const androidprojects=[
    {
        id:1,
        title:'',
        developer:'',
        projectImage:'',
        imageUrl:'',
        profileLink:'',
        projectLink:'',
    }
]
const uiuxprojects=[
    {
        id:1,
        title:'Weather Application UI',
        developer:'Abhinav',
        projectImage:'projects/uiux/weather.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/183013467/Futuristic-Weather-Website-UI',
    },
    {
        id:2,
        title:'Blog Haveli UI',
        developer:'Abhinav',
        projectImage:'projects/uiux/bloghaveli.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/183013089/Landing-page-for-a-SAAS-website',
    },
    {
        id:3,
        title:'Aavas Pro',
        developer:'Abhinav',
        projectImage:'projects/uiux/hostel.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/182999053/CRM-Portal',
    },
    {
        id:4,
        title:'Velvet Vibe Saloon Webiste',
        developer:'Abhinav',
        projectImage:'projects/uiux/velvet.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/182997243/Velvet-vibe-Saloon-website',
    },
    {
        id:5,
        title:'Nike Shopping UI',
        developer:'Abhinav',
        projectImage:'projects/uiux/nike.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/173851145/Nike-Shopping-website',
    },
    {
        id:6,
        title:'Nissan Car UI',
        developer:'Abhinav',
        projectImage:'projects/uiux/nissan.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/173715143/NIssan',
    },
    {
        id:7,
        title:'Wasruk Startup UI Design',
        developer:'Abhinav',
        projectImage:'projects/uiux/wasruk.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/173589699/Wasruk-Startup-UI-Design',
    },
    {
        id:8,
        title:'Develop It Community Page',
        developer:'Abhinav',
        projectImage:'projects/uiux/developit.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/173538839/Developit-Home-page',
    },
    {
        id:9,
        title:'THE UI LAB',
        developer:'Abhinav',
        projectImage:'projects/uiux/uilab.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/172908359/The_ui_lab',
    },
    {
        id:10,
        title:'Harmonize X',
        developer:'Abhinav',
        projectImage:'projects/uiux/harmonizex.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/162271959/HarmonizeX',
    },
    {
        id:11,
        title:'Choolha Chowka UI',
        developer:'Abhinav',
        projectImage:'projects/uiux/choolhachowka.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://choolhachowka.vercel.app',
    },
    {
        id:12,
        title:'Personal Portfolio',
        developer:'Abhinav',
        projectImage:'projects/uiux/portfolio.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQHtabWqzDOxjA/profile-displayphoto-shrink_400_400/0/1689803955352?e=1703116800&v=beta&t=CM9GszTUccY-btMTMZZTdd86uWSZpftvqUo8aYoFF1c',
        profileLink:'https://www.behance.net/abhinavfs',
        projectLink:'https://www.behance.net/gallery/175468345/portfolio-design',
    },

]
const webprojects=[
    {
        id:1,
        title:'Load It',
        developer:'Ayush Chauhan',
        projectImage:'projects/web/loadit.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQG-83phbPPI5A/profile-displayphoto-shrink_400_400/0/1675856946994?e=1703116800&v=beta&t=g27e6h_mylovfoGI3cvXbnt6LIdHu782F1EKKirXELs',
        profileLink:'https://www.linkedin.com/in/ayush-chauhan-bab008249/',
        projectLink:'https://github.com/Ayush-2301/load-it',
    },
    {
        id:2,
        title:'Musipedia',
        developer:'Ayush Chauhan',
        projectImage:'projects/web/musipedia.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQG-83phbPPI5A/profile-displayphoto-shrink_400_400/0/1675856946994?e=1703116800&v=beta&t=g27e6h_mylovfoGI3cvXbnt6LIdHu782F1EKKirXELs',
        profileLink:'https://www.linkedin.com/in/ayush-chauhan-bab008249/',
        projectLink:'https://github.com/Ayush-2301/Musipedia',
    },
    {
        id:3,
        title:'Blockchain Transaction Logger',
        developer:'Ayush Chauhan',
        projectImage:'projects/web/blockchainlogger.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQG-83phbPPI5A/profile-displayphoto-shrink_400_400/0/1675856946994?e=1703116800&v=beta&t=g27e6h_mylovfoGI3cvXbnt6LIdHu782F1EKKirXELs',
        profileLink:'https://www.linkedin.com/in/ayush-chauhan-bab008249/',
        projectLink:'https://github.com/Ayush-2301/web-3.0',
    },
    {
        id:4,
        title:'Sorting Visualizer',
        developer:'Ayush Chauhan',
        projectImage:'projects/web/sorting.jpg',
        imageUrl:'https://media.licdn.com/dms/image/D4D03AQG-83phbPPI5A/profile-displayphoto-shrink_400_400/0/1675856946994?e=1703116800&v=beta&t=g27e6h_mylovfoGI3cvXbnt6LIdHu782F1EKKirXELs',
        profileLink:'https://www.linkedin.com/in/ayush-chauhan-bab008249/',
        projectLink:'https://github.com/Ayush-2301/Sorting-Visualizer',
    },
    {
        id:5,
        title:'Choolha Chowka Website',
        developer:'Team NSCC',
        projectImage:'projects/web/choolhachowka.png',
        imageUrl:'',
        profileLink:'https://github.com/adityatyagi-av',
        projectLink:'https://choolhachowka.vercel.app/',
    },
]
export {aimlprojects,arvrprojects,androidprojects,webprojects,uiuxprojects};